import { loadAllMeta, type LoadedMeta } from "./load-meta";

export type GameEntry = {
  slug: string;
  title: string;
  tagline: string;
  image: string;
  playUrl: string;
  infoUrl?: string;
  category: string;
  tags: string[];
  model: string;
  featured?: boolean;
  // Optional richer fields populated from meta.yaml when available
  description?: string;
  features?: string[];
  controls?: string[];
  status?: string;
  version?: string;
  created?: string;
  updated?: string;
  provider?: string;
  chatUrl?: string;
};

export const socialLinks = {
  github: "https://github.com/HarmonicHemispheres/AI-Built-Games",
  linkedin: "https://www.linkedin.com/in/robby-boney-717486133/"
};

// Static defaults. Any matching meta.yaml file overrides these by slug.
// Games may eventually live entirely in meta.yaml; entries here are kept
// for back-compat with games that haven't been migrated yet.
const staticGames: GameEntry[] = [
  {
    slug: "merchant-seas",
    title: "Merchants of the High Seas",
    tagline: "Sail, trade, and battle across a procedurally generated nautical world.",
    image: "/games/merchant_seas/merchant_seas-banner.png",
    playUrl: "/games/merchant_seas/merchant_seas.html",
    category: "Strategy",
    tags: ["trading", "naval", "exploration"],
    model: "Unknown",
    featured: true
  },
  {
    slug: "memory-match",
    title: "Memory Match",
    tagline: "Flip cards, trigger specials, and beat your best turn count.",
    image: "/games/memory_match/memory-match-banner.png",
    playUrl: "/games/memory_match/game.html",
    infoUrl: "/games/memory_match/detail.html",
    category: "Puzzle",
    tags: ["cards", "memory", "single-player"],
    model: "Gemini 2.5 Pro",
    featured: true
  },
  {
    slug: "chess",
    title: "Chess",
    tagline: "Classic chess with a configurable modern browser board.",
    image: "/games/chess/banner.png",
    playUrl: "/games/chess/game.html",
    infoUrl: "/games/chess/detail.html",
    category: "Strategy",
    tags: ["board", "classic", "turn-based"],
    model: "Grok 3"
  },
  {
    slug: "basic-maze",
    title: "Basic Maze",
    tagline: "A fast, timed top-down maze run with adjustable challenge.",
    image: "/games/maze_basic/banner.png",
    playUrl: "/games/maze_basic/game.html",
    infoUrl: "/games/maze_basic/detail.html",
    category: "Maze",
    tags: ["arcade", "timed", "top-down"],
    model: "Grok 3"
  },
  {
    slug: "emojistry",
    title: "Emojistry",
    tagline: "Guess the topic from emoji clues generated by AI.",
    image: "/games/emojistry/banner.png",
    playUrl: "https://chatgpt.com/g/g-6740f24d4d548191a9c31accfdac5d3d-emojystry",
    infoUrl: "/games/emojistry/detail.html",
    category: "Word",
    tags: ["ai", "guessing", "party"],
    model: "GPT-4o"
  },
  {
    slug: "zombie-destroy",
    title: "2D Zombie Destroy",
    tagline: "Endless procedural rooms, upgrades, and zombie swarms.",
    image: "/games/inf_2d_explore_1/banner.png",
    playUrl: "/games/inf_2d_explore_1/game.html",
    infoUrl: "/games/inf_2d_explore_1/detail.html",
    category: "Action",
    tags: ["survival", "shooter", "procedural"],
    model: "OpenAI o1"
  },
  {
    slug: "circle-crush",
    title: "Circle Crush",
    tagline: "Match circles, chain bombs, and cash in multipliers.",
    image: "/games/circle_crush/banner.png",
    playUrl: "/games/circle_crush/game.html",
    infoUrl: "/games/circle_crush/detail.html",
    category: "Puzzle",
    tags: ["match-3", "casual", "score-attack"],
    model: "GPT-o1-preview"
  },
  {
    slug: "maze-runner-3d",
    title: "3D Maze Runner",
    tagline: "Navigate giant mazes, dodge zombies, survive deeper levels.",
    image: "/games/3d_maze/banner_2.png",
    playUrl: "/games/3d_maze/game.html",
    infoUrl: "/games/3d_maze/release_notes.html",
    category: "Maze",
    tags: ["3d", "survival", "shooter"],
    model: "GPT-o1-mini",
    featured: true
  },
  {
    slug: "tower-defense",
    title: "Tower Defense Example",
    tagline: "Build your lane defense and survive escalating waves.",
    image: "/games/tower_def_1/banner.png",
    playUrl: "/games/tower_def_1/game.html",
    infoUrl: "/games/tower_def_1/release_notes.html",
    category: "Strategy",
    tags: ["tower-defense", "waves", "upgrades"],
    model: "GPT-4o"
  },
  {
    slug: "economy-idle",
    title: "Economy IDLE",
    tagline: "Tile-based production chains with scaling taxes and upgrades.",
    image: "/games/economy_idle/banner.png",
    playUrl: "/games/economy_idle/index.html",
    infoUrl: "/games/economy_idle/release_notes.html",
    category: "Idle",
    tags: ["economy", "grid", "management"],
    model: "GPT-4o"
  },
  {
    slug: "wordl",
    title: "Wordl",
    tagline: "A quick daily-style word puzzle with adjustable length.",
    image: "/games/wordl/banner.png",
    playUrl: "/games/wordl/index.html",
    infoUrl: "/games/wordl/release_notes.html",
    category: "Word",
    tags: ["vocabulary", "daily", "puzzle"],
    model: "GPT-4o"
  },
  {
    slug: "something-fancy",
    title: "Something Fancy!",
    tagline: "Under development and cooking up something weird.",
    image: "/coming_soon_banner.png",
    playUrl: "/templates/under_development.html",
    category: "Prototype",
    tags: ["experimental", "coming-soon"],
    model: "TBD"
  }
];

function metaOverlay(meta: LoadedMeta): Partial<GameEntry> & { slug: string } {
  const folderPath = (file?: string) => (file ? `/games/${meta.folder}/${file}` : undefined);
  return {
    slug: meta.slug ?? meta.folder,
    title: meta.title,
    tagline: meta.tagline,
    image: folderPath(meta.banner),
    playUrl: folderPath(meta.entry),
    infoUrl: meta.info_url || undefined,
    category: meta.category,
    tags: meta.tags,
    featured: meta.featured,
    model: meta.built_with?.model,
    provider: meta.built_with?.provider,
    description: meta.description,
    features: meta.features,
    controls: meta.controls,
    status: meta.status,
    version: meta.version,
    created: meta.created,
    updated: meta.updated,
    chatUrl: meta.chat_url || undefined
  };
}

function applyOverlay(base: GameEntry, overlay: Partial<GameEntry>): GameEntry {
  const merged: GameEntry = { ...base };
  for (const [key, value] of Object.entries(overlay)) {
    if (value === undefined || value === null) continue;
    (merged as Record<string, unknown>)[key] = value;
  }
  return merged;
}

const overlayBySlug = new Map(loadAllMeta().map((m) => {
  const overlay = metaOverlay(m);
  return [overlay.slug, overlay] as const;
}));

const merged = staticGames.map((game) => {
  const overlay = overlayBySlug.get(game.slug);
  return overlay ? applyOverlay(game, overlay) : game;
});

const staticSlugs = new Set(staticGames.map((g) => g.slug));
const metaOnly: GameEntry[] = [...overlayBySlug.values()]
  .filter((o) => !staticSlugs.has(o.slug))
  .map((o) => ({
    slug: o.slug,
    title: o.title ?? o.slug,
    tagline: o.tagline ?? "",
    image: o.image ?? "/coming_soon_banner.png",
    playUrl: o.playUrl ?? "",
    category: o.category ?? "Other",
    tags: o.tags ?? [],
    model: o.model ?? "Unknown",
    featured: o.featured,
    description: o.description,
    features: o.features,
    controls: o.controls,
    status: o.status,
    version: o.version,
    created: o.created,
    updated: o.updated,
    provider: o.provider,
    chatUrl: o.chatUrl,
    infoUrl: o.infoUrl
  }));

export const games: GameEntry[] = [...merged, ...metaOnly];
